### ISSUE TITLE
Use Barlow as the default font

### ISSUE THREAD

**Issue by rlafuente** [faktenforum/faktenforum-frontend#16]
It is indeed defined in `assets/settings.scss`, but Vuetify is still loading with the default font (Roboto).

I spent a good couple of hours trying out different config options to override this, but no success. We can probably hardcode it, but I don't want to go ahead without your ok @likt0r :-)

**Comment by likt0r** [comment]
Hi Carlo, it seems to be a regression, i will investigate. We can talk about this in the meeting

**Comment by rlafuente** [comment]
Can confirm it's fixed, main branch now shows Barlow as expected :rocket:
