### ISSUE TITLE
Create Partner page

### ISSUE THREAD

**Issue by likt0r** [faktenforum/faktenforum-frontend#55]
- [ ] Create Partner Page
- [ ] Link from main Page
- [ ] Create Component feeded by google sheet

https://docs.google.com/spreadsheets/d/1lGnt5u7qmeO9ZtxlxlkMtdGqmNQPKR4VGi2HlsoB_ik/edit#gid=0

**Comment by CaLi-Correctiv** [comment]
- bilingual de/eng
- This is the doc with the structure: https://docs.google.com/document/d/1wDpL-KO4A9D-S4tvDmAmSORa6MaVA2FXblkXl9UXbwc/edit  
- button on top of main page / landing page "Über noFake"
